# 2. Exploratory Data Analysis (EDA)

In [16]:
import pandas as pd

user_file = "../data/raw_data/users.csv"
event_file = "../data/raw_data/events.csv"
session_file = "../data/raw_data/sessions.csv"
billing_file = "../data/raw_data/billing.csv"

user_df = pd.read_csv(user_file)
user_df

,user_id,signup_date,plan_tier,company_size,region,industry,acquisition_channel,is_enterprise,churned_30d,churned_90d,downgraded,expansion_event
0,f94d1824-8742-4000-8b6d-39d70958490b,2024-05-13,free,11-50,EU,software,seo,False,0,0,0,1
1,238bf0af-1f71-45e4-a47d-dcb5db33f71b,2025-04-11,standard,1-10,NaN,education,seo,False,0,0,0,0
2,ccf8fc06-3c86-433c-8867-9cba0fda337b,2024-10-28,free,1-10,APAC,transport,partner,False,0,0,0,1
3,3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10,2024-05-17,standard,200+,APAC,software,partner,False,0,0,0,1
4,9304dcbe-682d-41fa-8bfd-861559f9f58b,2024-04-12,free,1-10,NaN,software,ads,False,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
99995,e7e9d70c-478e-4d57-982a-53c98a175328,2024-09-17,premium,51-200,NaN,retail,partner,True,0,0,0,0
99996,1b74fc26-9c01-4aeb-95db-587abfda6e73,2024-04-29,free,11-50,NaN,finance,partner,False,0,1,0,1
99997,c209e590-7bcc-4aff-b3cd-c9c498491c22,2024-11-24,free,1-10,NaN,transport,seo,False,0,0,0,1
99998,06bde50d-e9b3-4db9-8353-cf0279d0060b,2025-05-01,premium,11-50,APAC,manufacturing,seo,False,0,0,0,0
99999,2bebcb3d-bead-492a-97e3-1346173ee638,2024-10-08,free,11-50,EU,software,partner,False,0,0,0,1

Looking at the metadata (README file), we see each file shows information about some user, specified by the "user_id" tag.

We want to extract the information available from each available file to see which variable and features leads to customers churning (our target variable in users.csv)

### How should we extract the information from each dataset?

We should take a look at each dataset

In [21]:
event_df = pd.read_csv(event_file)
event_df

,event_id,user_id,session_id,ts,feature_name,action,duration_ms,latency_ms,success
0,665ea739-d80e-4d68-b0be-67b74b79984a,3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10,e1c0b7e9-a987-43d6-8290-dc88c2cdf5c0,2024-05-28 01:39:27.377607462,jira_board,view,352,584,1
1,4259f36b-a4ec-41b2-9241-c2b90bf23f8c,3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10,e1c0b7e9-a987-43d6-8290-dc88c2cdf5c0,2024-05-28 01:41:27.463905173,jira_board,view,1053,382,1
2,c819fc5b-2d79-455a-9685-5347dae03f68,3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10,e1c0b7e9-a987-43d6-8290-dc88c2cdf5c0,2024-05-28 01:41:40.075644031,jira_automation,click,1185,103,1
3,c0ea5e8e-7236-4cd6-ab25-6c97b7f22465,3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10,32d59800-6d39-44b9-a439-49e3efc8409b,2024-05-21 14:51:02.758816559,jira_board,click,1772,169,1
4,96819e5e-edf0-4277-87c1-5c16235c9dff,3e39c0ea-ebbf-43bc-abd5-ab92eff6fa10,32d59800-6d39-44b9-a439-49e3efc8409b,2024-05-21 14:45:34.284688915,team_invite,click,480,302,1
...,...,...,...,...,...,...,...,...,...
234324,4493c55b-9e2d-4f81-a5b4-6b34b4539d83,e7e9d70c-478e-4d57-982a-53c98a175328,71fb51f1-a0b3-4775-9666-9dfb2058f734,2025-07-04 00:31:03.864056311,jira_board,view,386,441,1
234325,3df6c03f-3de8-4e6f-a392-3bee9bf72fdb,e7e9d70c-478e-4d57-982a-53c98a175328,27697c6f-b793-4f67-82d6-0e0f1a623267,2025-07-12 08:22:47.987536683,jira_automation,complete,758,185,1
234326,21ad6200-ffe7-46dd-8e67-75e57820c0d9,1b74fc26-9c01-4aeb-95db-587abfda6e73,7b167121-3a95-457e-8285-9152709f0efb,2024-12-03 04:52:48.701030271,confluence_page,view,599,211,1
234327,07c78acd-ffd1-434a-97fd-a759f37eafac,1b74fc26-9c01-4aeb-95db-587abfda6e73,7b167121-3a95-457e-8285-9152709f0efb,2024-12-03 04:54:16.733571952,confluence_ai_assist,complete,1990,185,1
234328,f1e90b20-a7f7-4950-a4bb-4c3e3f4d66a7,06bde50d-e9b3-4db9-8353-cf0279d0060b,321142e1-8d8a-43d6-988a-15084a61b64b,2025-07-04 05:52:05.198060420,jira_board,click,3275,402,1

### Train, Test (and sometimes Validation) Split

We need to avoid data leakage, and this is the primary goal of splitting our dataset

In [9]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=["mrr"])
y = df["mrr"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
X_train

,user_id,month,plan_tier,active_seats,discount_applied,invoices_overdue,support_ticket_count
655601,179a8233-a50f-4bbc-a224-b297f382555f,2025-05,premium,356,0,0,8
658606,2775fe29-24a9-4199-9e9f-20352dab9534,2024-05,premium,83,0,0,3
548034,c0c4bde8-fcb3-4b8d-8986-4f77fbb1e222,2024-04,free,6,0,0,0
455795,16337fb0-1c7f-4a03-a2e3-8de9e5a74322,2025-01,premium,26,0,0,1
372040,4a99a066-1b1b-4332-a6b9-175f69b1e792,2025-01,premium,22,0,0,0
...,...,...,...,...,...,...,...
259178,e7aef775-a275-4435-84ba-040aea75f3c9,2025-01,free,4,0,0,1
365838,06229124-65dd-44d6-a2c9-996c25442aaa,2025-04,premium,299,0,0,9
131932,f3c558c4-ca8c-4cf3-9092-6092cf0544c3,2024-12,free,9,0,0,0
671155,8d73f567-6fd8-44f6-b83d-056fe9a87ae8,2024-10,standard,3,0,0,0
121958,69e5f32c-ce15-4494-b58c-c60b9fd81e59,2024-07,standard,24,0,0,0